= Webpack Starter for Enonic XP
:toc: right1

Best practice project setup for building apps using Webpack.

NOTE: This starter requires Enonic XP 7.0.0 or later


== Introduction

Once initiated, you'll have the bare minimum needed to create a new Enonic
application with Webpack. You'll have all the folders set up, and can get
straight to creating what you're creating.

The project will support:

* Code minification;
* Production and development environments;
* SASS and Less support;
* Transpilation with Babel.


== Create a project

To setup a project locally, simply run the following command:

```bash
$ enonic project create
```
Complete the Wizard and make sure you choose *Webpack starter* from the list of starters

```bash
$ cd <project-folder>
```

NOTE: *Don't have the Enonic CLI?* Visit the https://developer.enonic.com/start[Getting started guide] to install it.


== Project structure

In the selected folder, you should now have a project structure, looking something like this:

.Selected files from the project structure:
[source,files]
----
src/
 main/
  resources/
   assets/
    js/
      example.js <!--1-->
      main.js <!--2-->
    styles/
      main.less <!--3-->
      main.sass <!--4-->
      main.scss <!--5-->
----

<1> Import example, that is imported in the `main.js`.
<2> Entry point of your application. Will be transpiled to the `assets/js/bundle.js`.
<3> Project styles in Less syntax.
<4> Project styles in SASS syntax.
<5> Project styles in SCSS syntax.


== Project bundling

Current configuration of the starter (`webpack.config.js`) is set up with the entry point of `main.js`. 

```js
module.exports = {
  context: path.join(__dirname, '/src/main/resources/assets'),
  entry: {
    bundle: './js/main.js',
  },
  // ...
}
```

This file can import other JavaScript files in your project, like `example.js`:

```js
import example from './example';
```

or even the assets like styles and fonts:

```js
import '../styles/main.less';
import '../styles/main.sass';
import '../styles/main.scss';
```

Starting from this entry point, webpack will recursively build a https://webpack.js.org/concepts/dependency-graph/[dependency graph] that includes every module your application needs, then bundle all of those modules into a small number of bundles (`bundle.js` and `bundle.css`) inside the `build` folder to be loaded by the browser.

.Build folder:
[source,files]
----
build/
 resources/
  main/
   assets/
    js/
      bundle.js
    styles/
      bundle.css
----

The resulting bundles must be included/imported in the HTML templates.

NOTE: Learn more about the webpack from the official https://webpack.js.org/concepts[docs].


== Building and Deploying

To *build* the app, run this command from your shell:

```bash
$ enonic project build
```

To *delete* the older build before you run a new one :

```bash
$ enonic project clean
```

To *deploy* the app, run this command from your shell:

```bash
$ enonic project deploy
```

After accepting starting the sandbox, your brand new app should now be up and running on http://localhost:8080

[NOTE]
====
To verify that your app started successfully, you should find an entry similar to this in the sandbox log:

  2019-04-30 14:26:30,856 INFO ... Application [com.acme.example.webpack] installed successfully
====

[TIP]
====
You can also combine several commands into one:

```bash
$ enonic project gradle clean build deploy
```
====


== Customizing build

=== Browserslist

The JS code will be transpiled by the Babel, according to the https://github.com/browserslist/browserslist[Browserslist] environment settings. That means, that you can use the *latest* EcmaScript syntax and the Babel will automatically transpile your code to Javascript supported by the browsers listed in the config. The CSS will be optimized, and all vendor prefixes will be automatically added, according to the supported browsers from the Browserslist configuration. By default, the starter extends the Enonic Browserslist configuration:

.package.json
```json
{
  ...
  "browserslist": [
    "extends browserslist-config-enonic"
  ],
  ...
}
```
See the official Browserslist https://github.com/browserslist/browserslist#browserslist-[documentation], if you want to change the configuration.

=== Less & Sass (Scss)

The starter supports Less, Sass, and Scss. But you probably won't be needing all of them. Just go to the `webpack.config.js`, drop the obsolete rule from the `module.rules` array and rename the remaining one. Also, don't forget to remove the corresponding node modules with the npm from the `package.json` for Less (`npm r less less-loader`) or Sass (`npm r node-sass sass-loader`).

=== Optimization

In the "production" mode, the Webpack will do multiple default https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions[optimizations] to the resulting JS, except removing the console methods calls from the code, because the corresponding options (`drop_console`) is set to `false`.


== Building for different environments

The project can also be built for different environments. To set the environment type, call the build with the `env` parameter. This parameter can be either `prod` ("production"), or `dev` ("development"). If the environment is not set explicitly, the "production" will be used by default. The environment can be accessed from Gradle and will also be passed to the webpack configuration.

Here is how you can run build in "development" mode:

```bash
$ enonic project gradle build -Penv=dev
```

In the "production" mode, all your code is minimized, dead code is removed, and no mappings are available.
